### ISSUE TITLE
Eye process not picking up new code after capistrano deployment

### ISSUE THREAD

**Issue by masone** [kostya/eye#95] opened 2014-12-01 07:25 UTC
We have recently migrated from foreman to eye and are very happy with the way we can manage our app related processed with it. Thanks!

Once in a while though, we run into `Bundler::GemfileNotFound` errors. It seems rather random. It can happen to only one eye process per application while all others of the same type stay alive. It also happens across eye applications and servers.

```
/usr/local/rvm/gems/ruby-2.0.0-p247@global/gems/bundler-1.7.2/lib/bundler/definition.rb:22:in `build': /home/xyz/web/releases/20141127222708/Gemfile not found (Bundler::GemfileNotFound)
	from /usr/local/rvm/gems/ruby-2.0.0-p247@global/gems/bundler-1.7.2/lib/bundler.rb:154:in `definition'
	from /usr/local/rvm/gems/ruby-2.0.0-p247@global/gems/bundler-1.7.2/lib/bundler.rb:117:in `setup'
from /usr/local/rvm/gems/ruby-2.0.0-p247@global/gems/bundler-1.7.2/lib/bundler/setup.rb:17:in `<top (required)>'
	from /usr/local/rvm/rubies/ruby-2.0.0-p247/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/rvm/rubies/ruby-2.0.0-p247/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
```

Here's an example of one process that runs into this problem a lot (simplified, not full config file).

```
EYE_ROOT = File.expand_path('~/web/current/') 

Eye.application("#{ENV['RAILS_ENV']}-worker") do

  working_dir EYE_ROOT

  process :facebook do
    start_command "bundle exec sidekiq -c 20 -q FriendUpdater -q Personcrawler"
    stop_signals [:USR1, 0, :TERM, 10.seconds, :KILL]

    daemonize true
    stop_on_delete true
    stdall "#{EYE_ROOT}/log/#{name}.log"
    pid_file "#{EYE_ROOT}/tmp/pids/#{name}.pid"
  end

end
```

We deploy with capistrano 3 and first `load` the eye configs, then `restart` the processes so they pick up the code changes. Here's our [full eye.rake](https://gist.github.com/masone/0e3dafb13a2ffc1d4a08)

```
  before :start, :load
  before :restart, :load
```

The way capistrano uses symlinks, it might happen that some process is pointing to a release directory that has been cleaned up in the meantime. As we load the config which freshly constructs the `EYE_ROOT` path, I cannot see how the process should have a reference to an old release. Also we restart the process which means that it picks up the changes from the fresh `current` symlink.

The solution usually is to `quit` / `load` / `restart` and everything works again for a while. But I think that's not the ideal workflow for deployments, right?

One usually sees the `Bundler::GemfileNotFound` error with unicorn. When killed with a `USR2`, even though code changes get picked up, the `BUNDLE_GEMFILE` env variable gets "cached" and needs therefore to be reset in the `before_exec` hook. This said, it's worth noting that we've never seen that problem with unicorn, but only plain ruby processes that get properly killed and started again.

Any ideas?

**Comment by kostya** [comment] 2015-01-31 22:14
any progress here?

**Comment by masone** [comment] 2015-02-09 14:57
Sorry for the delay and thanks for your help guys.
We have been successfully running for a long time now. Our workaround is to `quit` the daemon every time we are restarting the processes (first `quit`, then `load`, then `restart`). This doesn't make much sense but it worked so far.

@kostya Regarding your questions:
* We use `after 'deploy:published', 'eye:restart'` - so eye is restarted *after* the symlinks are changed
* We don't use any `ENV` variables except unicorns `BUNDLE_GEMFILE` (which is properly set)
* We are not using RVM but one single ruby version

What @nisanth074 is describing, is in line with my observations. Starting eye without bundler or having a global installation is not exactly what I want to do though. It defies the whole purpose of bundler. 

Apparently eye currently might not work out of the box with cap/bundler for all users. This is one of the most common setups though. Is there a any way to get eye to play nice with cap/bundler? I would welcome this a lot as it were a fool proof solution.

**Comment by kostya** [comment] 2015-02-09 18:04
if you are using `quit` something is very wrong.

did you try `clear_bundler_env`?

I not see anything bad in install eye as system wide tool, not from bundler. Just as any other system tools.

**Comment by jtomaszewski** [comment] 2015-02-15 23:32
In my case even `eye quit && eye load ... && eye restart` didn't help - the env `BUNDLE_GEMFILE` was still somewhere there in the eye's daemon. I had to replace it in eye's configuration file. @masone thanks for finding this!

I use eye (to run unicorn & sidekiq) in a similar way as @masone does. Without quitting the eye's process while reloading it, I almost always landed with some problem with wrong path to the app or something.
Here's my config to eye/unicorn config files, if someone's interested: https://gist.github.com/jtomaszewski/2bb75634200a41683afc

**Comment by kostya** [comment] 2015-02-16 13:29
@jtomaszewski, what the problem with path? what the in eye log? how to reproduce it?

**Comment by jtomaszewski** [comment] 2015-02-16 13:36
Something like this repeated a thousand of times (and similar with unicorn):
> Feb 16 00:22:13 staging.sampleapp.com eye.sidekiq:  /opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.8.2/lib/bundler/definition.rb:22:in `build': /u/apps/sampleapp/releases/20150214133010/Gemfile not found (Bundler::GemfileNotFound)
Feb 16 00:22:13 staging.sampleapp.com eye.sidekiq:    from /opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.8.2/lib/bundler.rb:155:in `definition'
Feb 16 00:22:13 staging.sampleapp.com eye.sidekiq:    from /opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.8.2/lib/bundler.rb:118:in `setup'
Feb 16 00:22:13 staging.sampleapp.com eye.sidekiq:    from /opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.8.2/lib/bundler/setup.rb:18:in `<top (required)>'
Feb 16 00:22:13 staging.sampleapp.com eye.sidekiq:    from /opt/rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
Feb 16 00:22:13 staging.sampleapp.com eye.sidekiq:    from /opt/rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
Feb 16 00:22:13 staging.sampleapp.com eye.sidekiq:    from /opt/rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
Feb 16 00:22:13 staging.sampleapp.com eye.sidekiq:    from bin/sidekiq:14:in `<main>'

But seems like the problem wasn't really there... [After I replaced](https://gist.github.com/jtomaszewski/2bb75634200a41683afc/revisions) `bin/sidekiq ...` with `bundle exec sidekiq` , the problem disappeared. No idea why I didn't use `bundle exec ...` there before, and why did it work for a long time and now it has been broken (maybe capistrano stopped recompiling the bundle gems if Gemfile hasn't been changed).

Anyway, now with explicit `BUNDLE_GEMFILE` variable being set, I'm pretty sure I shouldn't go into those problems again

**Comment by kostya** [comment] 2015-02-16 15:26
was 20150214133010 (in /u/apps/sampleapp/releases/20150214133010/Gemfile) previous deploy, and this problem happens when folder deleted?

**Comment by jtomaszewski** [comment] 2015-02-16 15:39
Yeah, the problem always appears after a `cap ... deploy` removes the previous release's directory and process still wants to be restarted in the old directory.

I didn't know about this `clear_bundler_env` method, I'll try it later. Seems like I missed it in the wiki section ;s

**Comment by kostya** [comment] 2015-02-16 15:51
process not restarted in the old directory, because, it every time do like this:
`cd working_dir && #{env_variables} #{start_command}`
so every time in new folder. but seems somewhere cached BUNDLE_GEMFILE

**Comment by jtomaszewski** [comment] 2015-02-17 11:19
Still, when I removed the `env "BUNDLE_GEMFILE" => "#{APP_PATH}/Gemfile"` line, it stopped working (even if I had inserted the `clear_bundler_env` line).

Conclusion: it's much better if the configuration file is more explicit:
```rb
  working_dir APP_PATH

  clear_bundler_env
  env "RAILS_ENV" => RAILS_ENV
  env "PATH" => "/opt/rbenv/shims:/opt/rbenv/bin:#{ENV['PATH']}"
  env "RBENV_ROOT" => "/opt/rbenv"
  env "RBENV_VERSION" => File.read("#{APP_PATH}/.ruby-version").strip
  env "BUNDLE_GEMFILE" => "#{APP_PATH}/Gemfile"
  # ...
  process :unicorn do
    pid_file "tmp/pids/unicorn.pid"
    start_command "bundle exec unicorn config.ru -Dc config/unicorn.rb -E #{RAILS_ENV}"
    # ...
  end
```
With this setup, it works completely.

**Comment by blackjid** [comment] 2015-03-16 13:28
@jtomaszewski in your latests configuration example, is the `APP_PATH` value equals to the capistrano `current` symlink??

**Comment by jtomaszewski** [comment] 2015-03-17 00:16
@blackjid Yes. You can see it here: https://gist.github.com/jtomaszewski/2bb75634200a41683afc

**Closed** 2015-05-17 00:30 UTC
Labels: question
